# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-09 14:29
from __future__ import unicode_literals

from django.db import migrations, models
import posts.models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0008_auto_20170209_1429'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_image',
            field=models.FileField(blank=True, null=True),
        ),
    ]
