# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-10 08:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0009_auto_20170209_1429'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_date',
            field=models.DateField(),
        ),
    ]
