# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-12 11:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0014_auto_20170212_1520'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parent_id', models.CharField(max_length=18)),
                ('file_name', models.CharField(max_length=100)),
                ('attachment', models.FileField(upload_to='post_image')),
            ],
        ),
    ]
