# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-14 05:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0017_auto_20170212_1648'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='post_image',
        ),
        migrations.AddField(
            model_name='post',
            name='post_image',
            field=models.ManyToManyField(blank=True, null=True, related_name='files', to='posts.Attachment'),
        ),
    ]
