# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-23 07:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0019_auto_20170214_0942'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Attachment',
        ),
    ]
