# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-04 16:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0025_auto_20170304_1459'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='post_date_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
